name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: idpp
            asset_name: idpp-x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: idpp
            asset_name: idpp-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: idpp
            asset_name: idpp-aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: idpp.exe
            asset_name: idpp-x86_64-pc-windows-msvc.exe

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename Artifact (Unix)
        if: matrix.os != 'windows-latest'
        run: mv target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ./${{ matrix.asset_name }}

      - name: Rename Artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: Move-Item -Path target\${{ matrix.target }}\release\${{ matrix.artifact_name }} -Destination .\${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
